UPDATE `command` SET `security`='10' WHERE (`name`='reset all');
UPDATE `command` SET `security`='5' WHERE (`name`='server exit');
UPDATE `command` SET `security`='4' WHERE (`name`='additem');
UPDATE `command` SET `security`='4' WHERE (`name`='additemset');
UPDATE `command` SET `security`='4' WHERE (`name`='aura');
UPDATE `command` SET `security`='4' WHERE (`name`='cast back');
UPDATE `command` SET `security`='4' WHERE (`name`='cast dist');
UPDATE `command` SET `security`='4' WHERE (`name`='cast self');
UPDATE `command` SET `security`='4' WHERE (`name`='cast target');
UPDATE `command` SET `security`='4' WHERE (`name`='cast');
UPDATE `command` SET `security`='4' WHERE (`name`='damage');
UPDATE `command` SET `security`='4' WHERE (`name`='die');
UPDATE `command` SET `security`='4' WHERE (`name`='learn all');
UPDATE `command` SET `security`='4' WHERE (`name`='learn');
UPDATE `command` SET `security`='4' WHERE (`name`='send items');
UPDATE `command` SET `security`='4' WHERE (`name`='honor add');
UPDATE `command` SET `security`='4' WHERE (`name`='honor addkill');
UPDATE `command` SET `security`='4' WHERE (`name`='npc additem');
UPDATE `command` SET `security`='4' WHERE (`name`='modify arena');
UPDATE `command` SET `security`='4' WHERE (`name`='modify honor');
UPDATE `command` SET `security`='4' WHERE (`name`='server restart cancel');
UPDATE `command` SET `security`='4' WHERE (`name`='server restart');
UPDATE `command` SET `security`='4' WHERE (`name`='server set closed');
UPDATE `command` SET `security`='5' WHERE (`name`='server shutdown cancel');
UPDATE `command` SET `security`='5' WHERE (`name`='server shutdown');
UPDATE `command` SET `security`='4' WHERE (`name`='server idlerestart cancel');
UPDATE `command` SET `security`='4' WHERE (`name`='server idlerestart');
UPDATE `command` SET `security`='4' WHERE (`name`='server idleshutdown cancel');
UPDATE `command` SET `security`='4' WHERE (`name`='server idleshutdown');
